name = "cardano-foundation/cip113-programmable-tokens"
version = "0.5.0-alpha.2"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken implementation of CIP-113 programmable tokens"

[repository]
user = "cardano-foundation"
project = "cip113-programmable-tokens"
platform = "github"

[[dependencies]]
name = "easy1staking-com/stdlib"
version = "feat/native-value-builtins"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"

[config]
